from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clavier(object):
    def setupUi(self, clavier):

        clavier.setObjectName("clavier")
        self.Ech = QtWidgets.QPushButton(clavier)
        self.Ech.setGeometry(QtCore.QRect(0, 90, 31, 41))
        self.Ech.setObjectName("Ech")
        self.pushButton_2 = QtWidgets.QPushButton(clavier)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 250, 31, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(clavier)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 250, 41, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(clavier)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 250, 41, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(clavier)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 250, 31, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(clavier)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 250, 151, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(clavier)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 250, 31, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(clavier)
        self.pushButton_8.setGeometry(QtCore.QRect(350, 250, 31, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(clavier)
        self.pushButton_9.setGeometry(QtCore.QRect(380, 250, 31, 41))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(clavier)
        self.pushButton_10.setGeometry(QtCore.QRect(410, 250, 31, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(clavier)
        self.pushButton_11.setGeometry(QtCore.QRect(320, 250, 31, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(clavier)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 210, 51, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(clavier)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 210, 41, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(clavier)
        self.pushButton_14.setGeometry(QtCore.QRect(110, 210, 31, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(clavier)
        self.pushButton_15.setGeometry(QtCore.QRect(80, 210, 31, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(clavier)
        self.pushButton_16.setGeometry(QtCore.QRect(140, 210, 31, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(clavier)
        self.pushButton_17.setGeometry(QtCore.QRect(170, 210, 31, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(clavier)
        self.pushButton_18.setGeometry(QtCore.QRect(200, 210, 31, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(clavier)
        self.pushButton_19.setGeometry(QtCore.QRect(380, 210, 31, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(clavier)
        self.pushButton_20.setGeometry(QtCore.QRect(230, 210, 31, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(clavier)
        self.pushButton_21.setGeometry(QtCore.QRect(260, 210, 31, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(clavier)
        self.pushButton_22.setGeometry(QtCore.QRect(290, 210, 31, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(clavier)
        self.pushButton_23.setGeometry(QtCore.QRect(320, 210, 31, 41))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(clavier)
        self.pushButton_24.setGeometry(QtCore.QRect(350, 210, 31, 41))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(clavier)
        self.pushButton_25.setGeometry(QtCore.QRect(410, 210, 31, 41))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(clavier)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 170, 71, 41))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(clavier)
        self.pushButton_27.setGeometry(QtCore.QRect(70, 170, 31, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(clavier)
        self.pushButton_28.setGeometry(QtCore.QRect(100, 170, 31, 41))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(clavier)
        self.pushButton_29.setGeometry(QtCore.QRect(130, 170, 31, 41))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(clavier)
        self.pushButton_30.setGeometry(QtCore.QRect(160, 170, 31, 41))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(clavier)
        self.pushButton_31.setGeometry(QtCore.QRect(190, 170, 31, 41))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(clavier)
        self.pushButton_32.setGeometry(QtCore.QRect(220, 170, 31, 41))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(clavier)
        self.pushButton_33.setGeometry(QtCore.QRect(250, 170, 31, 41))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(clavier)
        self.pushButton_34.setGeometry(QtCore.QRect(280, 170, 31, 41))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(clavier)
        self.pushButton_35.setGeometry(QtCore.QRect(310, 170, 31, 41))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(clavier)
        self.pushButton_36.setGeometry(QtCore.QRect(340, 170, 31, 41))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(clavier)
        self.pushButton_37.setGeometry(QtCore.QRect(370, 170, 31, 41))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(clavier)
        self.pushButton_38.setGeometry(QtCore.QRect(400, 130, 41, 81))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(clavier)
        self.pushButton_39.setGeometry(QtCore.QRect(0, 130, 41, 41))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(clavier)
        self.pushButton_40.setGeometry(QtCore.QRect(40, 130, 31, 41))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(clavier)
        self.pushButton_41.setGeometry(QtCore.QRect(70, 130, 31, 41))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(clavier)
        self.pushButton_42.setGeometry(QtCore.QRect(100, 130, 31, 41))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(clavier)
        self.pushButton_43.setGeometry(QtCore.QRect(130, 130, 31, 41))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(clavier)
        self.pushButton_44.setGeometry(QtCore.QRect(160, 130, 31, 41))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(clavier)
        self.pushButton_45.setGeometry(QtCore.QRect(190, 130, 31, 41))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(clavier)
        self.pushButton_46.setGeometry(QtCore.QRect(220, 130, 31, 41))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(clavier)
        self.pushButton_47.setGeometry(QtCore.QRect(250, 130, 31, 41))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(clavier)
        self.pushButton_48.setGeometry(QtCore.QRect(280, 130, 31, 41))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(clavier)
        self.pushButton_49.setGeometry(QtCore.QRect(310, 130, 31, 41))
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(clavier)
        self.pushButton_50.setGeometry(QtCore.QRect(340, 130, 31, 41))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(clavier)
        self.pushButton_51.setGeometry(QtCore.QRect(370, 130, 31, 41))
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(clavier)
        self.pushButton_52.setGeometry(QtCore.QRect(30, 90, 31, 41))
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(clavier)
        self.pushButton_53.setGeometry(QtCore.QRect(60, 90, 31, 41))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(clavier)
        self.pushButton_54.setGeometry(QtCore.QRect(90, 90, 31, 41))
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(clavier)
        self.pushButton_55.setGeometry(QtCore.QRect(120, 90, 31, 41))
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(clavier)
        self.pushButton_56.setGeometry(QtCore.QRect(150, 90, 31, 41))
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(clavier)
        self.pushButton_57.setGeometry(QtCore.QRect(180, 90, 31, 41))
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(clavier)
        self.pushButton_58.setGeometry(QtCore.QRect(210, 90, 31, 41))
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(clavier)
        self.pushButton_59.setGeometry(QtCore.QRect(240, 90, 31, 41))
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(clavier)
        self.pushButton_60.setGeometry(QtCore.QRect(270, 90, 31, 41))
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_61 = QtWidgets.QPushButton(clavier)
        self.pushButton_61.setGeometry(QtCore.QRect(300, 90, 31, 41))
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(clavier)
        self.pushButton_62.setGeometry(QtCore.QRect(330, 90, 31, 41))
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton = QtWidgets.QPushButton(clavier)
        self.pushButton.setGeometry(QtCore.QRect(360, 90, 31, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_63 = QtWidgets.QPushButton(clavier)
        self.pushButton_63.setGeometry(QtCore.QRect(390, 90, 51, 41))
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(clavier)
        self.pushButton_64.setGeometry(QtCore.QRect(440, 250, 91, 41))
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(clavier)
        self.pushButton_65.setGeometry(QtCore.QRect(530, 250, 31, 41))
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_66 = QtWidgets.QPushButton(clavier)
        self.pushButton_66.setGeometry(QtCore.QRect(560, 210, 41, 81))
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_67 = QtWidgets.QPushButton(clavier)
        self.pushButton_67.setGeometry(QtCore.QRect(440, 210, 41, 41))
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_68 = QtWidgets.QPushButton(clavier)
        self.pushButton_68.setGeometry(QtCore.QRect(480, 210, 41, 41))
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(clavier)
        self.pushButton_69.setGeometry(QtCore.QRect(520, 210, 41, 41))
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(clavier)
        self.pushButton_70.setGeometry(QtCore.QRect(560, 130, 41, 81))
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_71 = QtWidgets.QPushButton(clavier)
        self.pushButton_71.setGeometry(QtCore.QRect(440, 170, 41, 41))
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_72 = QtWidgets.QPushButton(clavier)
        self.pushButton_72.setGeometry(QtCore.QRect(480, 170, 41, 41))
        self.pushButton_72.setObjectName("pushButton_72")
        self.pushButton_73 = QtWidgets.QPushButton(clavier)
        self.pushButton_73.setGeometry(QtCore.QRect(520, 170, 41, 41))
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_74 = QtWidgets.QPushButton(clavier)
        self.pushButton_74.setGeometry(QtCore.QRect(440, 130, 41, 41))
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_75 = QtWidgets.QPushButton(clavier)
        self.pushButton_75.setGeometry(QtCore.QRect(480, 130, 41, 41))
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_76 = QtWidgets.QPushButton(clavier)
        self.pushButton_76.setGeometry(QtCore.QRect(520, 130, 41, 41))
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_77 = QtWidgets.QPushButton(clavier)
        self.pushButton_77.setGeometry(QtCore.QRect(440, 90, 41, 41))
        self.pushButton_77.setObjectName("pushButton_77")
        self.pushButton_78 = QtWidgets.QPushButton(clavier)
        self.pushButton_78.setGeometry(QtCore.QRect(480, 90, 41, 41))
        self.pushButton_78.setObjectName("pushButton_78")
        self.pushButton_79 = QtWidgets.QPushButton(clavier)
        self.pushButton_79.setGeometry(QtCore.QRect(520, 90, 41, 41))
        self.pushButton_79.setObjectName("pushButton_79")
        self.pushButton_80 = QtWidgets.QPushButton(clavier)
        self.pushButton_80.setGeometry(QtCore.QRect(560, 90, 41, 41))
        self.pushButton_80.setObjectName("pushButton_80")
        self.textEdit = QtWidgets.QTextEdit(clavier)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 601, 91))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(clavier)
        QtCore.QMetaObject.connectSlotsByName(clavier)

    def retranslateUi(self, clavier):
        _translate = QtCore.QCoreApplication.translate
        clavier.setWindowTitle(_translate("TeKeyboard", "TeKeyboard"))
        self.Ech.setText(_translate("clavier", "Ech"))
        self.pushButton_2.setText(_translate("clavier", "fn"))
        self.pushButton_3.setText(_translate("clavier", "CTRL"))
        self.pushButton_4.setText(_translate("clavier", "W"))
        self.pushButton_5.setText(_translate("clavier", "Alt"))
        self.pushButton_6.setText(_translate("clavier", "Espace"))
        self.pushButton_7.setText(_translate("clavier", "Alt"))
        self.pushButton_8.setText(_translate("clavier", "<"))
        self.pushButton_10.setText(_translate("clavier", ">"))
        self.pushButton_11.setText(_translate("clavier", "L"))
        self.pushButton_12.setText(_translate("clavier", "Maj"))
        self.pushButton_13.setText(_translate("clavier", ">"))
        self.pushButton_14.setText(_translate("clavier", "w"))
        self.pushButton_15.setText(_translate("clavier", "c"))
        self.pushButton_16.setText(_translate("clavier", "v"))
        self.pushButton_17.setText(_translate("clavier", "n"))
        self.pushButton_18.setText(_translate("clavier", "b"))
        self.pushButton_19.setText(_translate("clavier", "^"))
        self.pushButton_20.setText(_translate("clavier", "n"))
        self.pushButton_21.setText(_translate("clavier", ","))
        self.pushButton_22.setText(_translate("clavier", ";"))
        self.pushButton_23.setText(_translate("clavier", ":"))
        self.pushButton_24.setText(_translate("clavier", "!"))
        self.pushButton_25.setText(_translate("clavier", "Maj"))
        self.pushButton_26.setText(_translate("clavier", "Caps Lock"))
        self.pushButton_27.setText(_translate("clavier", "q"))
        self.pushButton_28.setText(_translate("clavier", "s"))
        self.pushButton_29.setText(_translate("clavier", "d"))
        self.pushButton_30.setText(_translate("clavier", "f"))
        self.pushButton_31.setText(_translate("clavier", "g"))
        self.pushButton_32.setText(_translate("clavier", "h"))
        self.pushButton_33.setText(_translate("clavier", "j"))
        self.pushButton_34.setText(_translate("clavier", "k"))
        self.pushButton_35.setText(_translate("clavier", "l"))
        self.pushButton_36.setText(_translate("clavier", "m"))
        self.pushButton_37.setText(_translate("clavier", "ù"))
        self.pushButton_38.setText(_translate("clavier", "Entrée"))
        self.pushButton_39.setText(_translate("clavier", "Tab"))
        self.pushButton_40.setText(_translate("clavier", "a"))
        self.pushButton_41.setText(_translate("clavier", "z"))
        self.pushButton_42.setText(_translate("clavier", "e"))
        self.pushButton_43.setText(_translate("clavier", "z"))
        self.pushButton_44.setText(_translate("clavier", "r"))
        self.pushButton_45.setText(_translate("clavier", "t"))
        self.pushButton_46.setText(_translate("clavier", "y"))
        self.pushButton_47.setText(_translate("clavier", "i"))
        self.pushButton_48.setText(_translate("clavier", "o"))
        self.pushButton_49.setText(_translate("clavier", "p"))
        self.pushButton_50.setText(_translate("clavier", "^"))
        self.pushButton_51.setText(_translate("clavier", "$"))
        self.pushButton_52.setText(_translate("clavier", "&&"))
        self.pushButton_53.setText(_translate("clavier", "é"))
        self.pushButton_54.setText(_translate("clavier", "\""))
        self.pushButton_55.setText(_translate("clavier", "\'"))
        self.pushButton_56.setText(_translate("clavier", "("))
        self.pushButton_57.setText(_translate("clavier", "-"))
        self.pushButton_58.setText(_translate("clavier", "é"))
        self.pushButton_59.setText(_translate("clavier", "_"))
        self.pushButton_60.setText(_translate("clavier", "ç"))
        self.pushButton_61.setText(_translate("clavier", "à"))
        self.pushButton_62.setText(_translate("clavier", ")"))
        self.pushButton.setText(_translate("clavier", "="))
        self.pushButton_63.setText(_translate("clavier", "="))
        self.pushButton_64.setText(_translate("clavier", "0"))
        self.pushButton_65.setText(_translate("clavier", "."))
        self.pushButton_66.setText(_translate("clavier", "Entrée"))
        self.pushButton_67.setText(_translate("clavier", "1"))
        self.pushButton_68.setText(_translate("clavier", "2"))
        self.pushButton_69.setText(_translate("clavier", "3"))
        self.pushButton_70.setText(_translate("clavier", "+"))
        self.pushButton_71.setText(_translate("clavier", "4"))
        self.pushButton_72.setText(_translate("clavier", "5"))
        self.pushButton_73.setText(_translate("clavier", "6"))
        self.pushButton_74.setText(_translate("clavier", "7"))
        self.pushButton_75.setText(_translate("clavier", "8"))
        self.pushButton_76.setText(_translate("clavier", "9"))
        self.pushButton_77.setText(_translate("clavier", "Num"))
        self.pushButton_78.setText(_translate("clavier", "/"))
        self.pushButton_79.setText(_translate("clavier", "*"))
        self.pushButton_80.setText(_translate("clavier", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    clavier = QtWidgets.QWidget()
    ui = Ui_clavier()
    ui.setupUi(clavier)
    clavier.show()
    sys.exit(app.exec_())

